accounts:
  okx:
    main:
      api_key: "your_api_key"
      api_secret: "your_api_secret"
      passphrase: "your_passphrase"
    sub1:
      api_key: "sub_account_api_key"
      api_secret: "sub_account_api_secret"
      passphrase: "sub_account_passphrase"
  backpack:
    main:
      public_key: "your_public_key"
      secret_key: "your_secret_key"
    arb_bot:
      public_key: "bot_public_key"
      secret_key: "bot_secret_key"
    accounts:
 
